name: Test e2e aggOracle
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}

env:
  POLYCLI_VERSION: v0.1.67

jobs:
  build-aggkit-image:
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.22.x
      docker-image-name: aggkit

  test-e2e-aggoracle:
    needs: build-aggkit-image
    runs-on: amd-runner-2204
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        e2e-group:
          - fork12-multi-pessimistic
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
    
    - name: Build Tools
      run: make build-tools
      
    - name: Checkout Kurtosis CDK
      uses: actions/checkout@v4
      with:
        repository: 0xPolygon/kurtosis-cdk
        path: kurtosis-cdk
        ref: cb8e973dd11d030e06920822fec9c337be8c24f9
    
    # - name: Install polycli
    #   run: |
    #     tmp_dir=$(mktemp -d) 
    #     curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${{ env.POLYCLI_VERSION }}/polycli_${{ env.POLYCLI_VERSION }}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir" 
    #     mv "$tmp_dir"/* /usr/local/bin/polycli 
    #     rm -rf "$tmp_dir"
    #     sudo chmod +x /usr/local/bin/polycli
    #     /usr/local/bin/polycli version

    - name: Install Kurtosis CDK tools
      uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk

    - name: Setup Bats and bats libs
      uses: bats-core/bats-action@2.0.0
    
    - name: Download aggkit archive
      uses: actions/download-artifact@v4
      with:
        name: aggkit
        path: /tmp

    - name: Load aggkit image
      run: |
        docker load --input /tmp/aggkit.tar
        docker image ls -a

    - name: Run E2E tests
      run: make test-e2e-aggoracle
      working-directory: test
      env:
        KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
        BATS_LIB_PATH: /usr/lib/
        AGGLAYER_PROVER_SP1_KEY: ${{ secrets.SP1_PRIVATE_KEY }}
    
    - name: Dump enclave logs
      if: failure()
      run: kurtosis dump ./dump
  
    - name: Generate archive name
      if: failure()
      run: |
        archive_name="dump_run_with_args_${{matrix.e2e-group}}_${{ github.run_id }}"
        echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
        echo "Generated archive name: ${archive_name}"
  
    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ./dump
